// <auto-generated />
namespace TamagotchiService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201601101846 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201601101846));
        
        string IMigrationMetadata.Id
        {
            get { return "201601101746300_201601101846"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
